In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
df = pd.read_csv("../data/Amazon_Reviews_u.csv")

In [24]:
df.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
0,Lisa,/users/63c2d28aff751c001470ce46,US,1 review,2023-01-14T18:41:59.000Z,1.0,What happened to quality customer service?,"I ordered several items on Jan 2, this review ...","January 14, 2023"
1,J Ellery,/users/4f5291a30000640001153f96,GB,6 reviews,2012-03-03T21:50:56.000Z,5.0,Best on the web,Never any problems.goods always arrive when st...,"March 03, 2012"
2,Heather Weber,/users/5d37078e6614abe3ab453adf,US,1 review,2019-07-23T13:12:41.000Z,3.0,Issues with online purchases,"Recently, I have been having issues with my or...","July 23, 2019"
3,Mrs Lowe,/users/5666ab6d0000ff0001f14958,GB,2 reviews,2015-12-08T10:07:54.695Z,5.0,Excellent as always,Very good.,NaN
4,Lolo Paz,/users/5d8732fb681610d90db66d2e,US,2 reviews,2019-09-22T08:41:50.000Z,4.0,Ive been shopping with amazon for…,Ive been shopping with amazon for almost a yea...,"September 22, 2019"

In [25]:
df.shape

(42753, 9)

In [26]:
df.columns

Index(['Reviewer Name', 'Profile Link', 'Country', 'Review Count',
       'Review Date', 'Rating', 'Review Title', 'Review Text',
       'Date of Experience'],
      dtype='object')

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42753 entries, 0 to 42752
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reviewer Name       42753 non-null  object
 1   Profile Link        42753 non-null  object
 2   Country             42750 non-null  object
 3   Review Count        42753 non-null  object
 4   Review Date         42753 non-null  object
 5   Rating              42740 non-null  float64
 6   Review Title        42753 non-null  object
 7   Review Text         42753 non-null  object
 8   Date of Experience  41649 non-null  object
dtypes: float64(1), object(8)
memory usage: 2.9+ MB

In [28]:
df.isnull().sum()

Reviewer Name            0
Profile Link             0
Country                  3
Review Count             0
Review Date              0
Rating                  13
Review Title             0
Review Text              0
Date of Experience    1104
dtype: int64

In [29]:
df.dropna(subset=['Review Text', 'Rating'], inplace=True)

In [30]:
df.duplicated().sum()

np.int64(0)

In [31]:
df['Rating'].head(10)

0    1.0
1    5.0
2    3.0
3    5.0
4    4.0
5    1.0
6    1.0
7    5.0
8    1.0
9    1.0
Name: Rating, dtype: float64

In [32]:
df['Rating'] = df['Rating'].astype(str).str.extract('(\d+)')

In [33]:
df['Rating'] = pd.to_numeric(df['Rating'])

In [34]:
df['Rating'].head(10)

0    1
1    5
2    3
3    5
4    4
5    1
6    1
7    5
8    1
9    1
Name: Rating, dtype: int64

In [35]:
def sentiment_label(rating):

    if rating <= 2:
        return "Negative"

    elif rating == 3:
        return "Neutral"

    else:
        return "Positive"

In [36]:
df['Sentiment'] = df['Rating'].apply(sentiment_label)

In [37]:
df[['Rating','Sentiment']].head()

   Rating Sentiment
0       1  Negative
1       5  Positive
2       3   Neutral
3       5  Positive
4       4  Positive

In [38]:
df['Sentiment'].value_counts()

Sentiment
Positive    17923
Negative    14349
Neutral     10468
Name: count, dtype: int64

In [39]:
df = df[df['Reviewer Name'] != 'Reviewer Name']

In [40]:
df.reset_index(drop=True, inplace=True)

In [41]:
df.shape

(42740, 10)

In [42]:
df.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience,Sentiment
0,Lisa,/users/63c2d28aff751c001470ce46,US,1 review,2023-01-14T18:41:59.000Z,1,What happened to quality customer service?,"I ordered several items on Jan 2, this review ...","January 14, 2023",Negative
1,J Ellery,/users/4f5291a30000640001153f96,GB,6 reviews,2012-03-03T21:50:56.000Z,5,Best on the web,Never any problems.goods always arrive when st...,"March 03, 2012",Positive
2,Heather Weber,/users/5d37078e6614abe3ab453adf,US,1 review,2019-07-23T13:12:41.000Z,3,Issues with online purchases,"Recently, I have been having issues with my or...","July 23, 2019",Neutral
3,Mrs Lowe,/users/5666ab6d0000ff0001f14958,GB,2 reviews,2015-12-08T10:07:54.695Z,5,Excellent as always,Very good.,NaN,Positive
4,Lolo Paz,/users/5d8732fb681610d90db66d2e,US,2 reviews,2019-09-22T08:41:50.000Z,4,Ive been shopping with amazon for…,Ive been shopping with amazon for almost a yea...,"September 22, 2019",Positive

In [43]:
df.to_csv("../data/cleaned_reviews.csv", index=False)