In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("../data/Amazon_Reviews.csv")

In [4]:
df.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience
0,Eugene ath,/users/66e8185ff1598352d6b3701a,US,1 review,2024-09-16T13:44:26.000Z,Rated 1 out of 5 stars,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ...","September 16, 2024"
1,Daniel ohalloran,/users/5d75e460200c1f6a6373648c,GB,9 reviews,2024-09-16T18:26:46.000Z,Rated 1 out of 5 stars,Had multiple orders one turned up and…,Had multiple orders one turned up and driver h...,"September 16, 2024"
2,p fisher,/users/546cfcf1000064000197b88f,GB,90 reviews,2024-09-16T21:47:39.000Z,Rated 1 out of 5 stars,I informed these reprobates,I informed these reprobates that I WOULD NOT B...,"September 16, 2024"
3,Greg Dunn,/users/62c35cdbacc0ea0012ccaffa,AU,5 reviews,2024-09-17T07:15:49.000Z,Rated 1 out of 5 stars,Advertise one price then increase it on website,I have bought from Amazon before and no proble...,"September 17, 2024"
4,Sheila Hannah,/users/5ddbe429478d88251550610e,GB,8 reviews,2024-09-16T18:37:17.000Z,Rated 1 out of 5 stars,If I could give a lower rate I would,If I could give a lower rate I would! I cancel...,"September 16, 2024"

In [5]:
df.shape

(21656, 9)

In [6]:
df.columns

Index(['Reviewer Name', 'Profile Link', 'Country', 'Review Count',
       'Review Date', 'Rating', 'Review Title', 'Review Text',
       'Date of Experience'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21656 entries, 0 to 21655
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reviewer Name       21656 non-null  object
 1   Profile Link        21515 non-null  object
 2   Country             21219 non-null  object
 3   Review Count        21133 non-null  object
 4   Review Date         21091 non-null  object
 5   Rating              21075 non-null  object
 6   Review Title        21065 non-null  object
 7   Review Text         21061 non-null  object
 8   Date of Experience  20733 non-null  object
dtypes: object(9)
memory usage: 1.5+ MB

In [8]:
df.isnull().sum()

Reviewer Name           0
Profile Link          141
Country               437
Review Count          523
Review Date           565
Rating                581
Review Title          591
Review Text           595
Date of Experience    923
dtype: int64

In [9]:
df.dropna(subset=['Review Text', 'Rating'], inplace=True)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df['Rating'].head(10)

0    Rated 1 out of 5 stars
1    Rated 1 out of 5 stars
2    Rated 1 out of 5 stars
3    Rated 1 out of 5 stars
4    Rated 1 out of 5 stars
5    Rated 1 out of 5 stars
6    Rated 1 out of 5 stars
7    Rated 5 out of 5 stars
8    Rated 1 out of 5 stars
9    Rated 5 out of 5 stars
Name: Rating, dtype: object

In [12]:
df['Rating'] = df['Rating'].astype(str).str.extract('(\d+)')

In [13]:
df['Rating'] = pd.to_numeric(df['Rating'])

In [19]:
df['Rating'].head(10)

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    5.0
8    1.0
9    5.0
Name: Rating, dtype: float64

In [15]:
def sentiment_label(rating):

    if rating <= 2:
        return "Negative"

    elif rating == 3:
        return "Neutral"

    else:
        return "Positive"

In [16]:
df['Sentiment'] = df['Rating'].apply(sentiment_label)

In [17]:
df[['Rating', 'Sentiment']].head()

   Rating Sentiment
0     1.0  Negative
1     1.0  Negative
2     1.0  Negative
3     1.0  Negative
4     1.0  Negative

In [20]:
df['Sentiment'].value_counts()

Sentiment
Negative    14349
Positive     5827
Neutral       885
Name: count, dtype: int64

In [29]:
df = df[df['Reviewer Name'] != 'Reviewer Name']

In [30]:
df.reset_index(drop=True, inplace=True)

In [31]:
df.shape

(21061, 10)

In [33]:
df.head()

,Reviewer Name,Profile Link,Country,Review Count,Review Date,Rating,Review Title,Review Text,Date of Experience,Sentiment
0,Eugene ath,/users/66e8185ff1598352d6b3701a,US,1 review,2024-09-16T13:44:26.000Z,1.0,A Store That Doesn't Want to Sell Anything,"I registered on the website, tried to order a ...","September 16, 2024",Negative
1,Daniel ohalloran,/users/5d75e460200c1f6a6373648c,GB,9 reviews,2024-09-16T18:26:46.000Z,1.0,Had multiple orders one turned up and…,Had multiple orders one turned up and driver h...,"September 16, 2024",Negative
2,p fisher,/users/546cfcf1000064000197b88f,GB,90 reviews,2024-09-16T21:47:39.000Z,1.0,I informed these reprobates,I informed these reprobates that I WOULD NOT B...,"September 16, 2024",Negative
3,Greg Dunn,/users/62c35cdbacc0ea0012ccaffa,AU,5 reviews,2024-09-17T07:15:49.000Z,1.0,Advertise one price then increase it on website,I have bought from Amazon before and no proble...,"September 17, 2024",Negative
4,Sheila Hannah,/users/5ddbe429478d88251550610e,GB,8 reviews,2024-09-16T18:37:17.000Z,1.0,If I could give a lower rate I would,If I could give a lower rate I would! I cancel...,"September 16, 2024",Negative

In [36]:
df.to_csv("../data/cleaned_reviews.csv", index=False)